require_relative '../tests/image/image_spec.rb'
require_relative '../tests/networkcontroller/networkcontroller_spec.rb'
require_relative '../tests/orchestrationapi/orchestrationapi_spec.rb'
require_relative '../tests/telemetryserver/telemetryserver_spec.rb'
require_relative '../tests/controller/controller_spec.rb'
